language: android

sudo: false

android:
  components:
    - platform-tools
    - build-tools-35.0.0
    - android-35
    - extra-android-support
  licenses:
    - '.+'

script:
 - ./gradlew clean testDebugUnitTest --stacktrace
    
notifications:
  email: false
